---
- name: Copy executable
  copy:
    src: "{{ playbook_dir }}/../bin/Release/netcoreapp3.1/linux-x64/publish/Pley"
    dest: /home/centos
    owner: centos
    group: centos
    mode: 0744

- name: Copy appsettings
  copy:
    src: "{{ playbook_dir }}/../bin/Release/netcoreapp3.1/linux-x64/publish/appsettings.json"
    dest: /home/centos
    group: centos
    owner: centos

- name: Copy appsettings.Production
  template:
    src: "appsettings.Production.json.j2"
    dest: /home/centos/appsettings.Production.json
    owner: centos
    group: centos

- name: Copy ClientApp
  copy:
    src: "{{ playbook_dir }}/../ClientApp/build"
    dest: /home/centos/ClientApp
    owner: centos
    group: centos
